name = "wechaty-js-org"
compatibility_date = "2025-01-01"

# Cloudflare Pages uses this to detect project root
pages_build_output_dir = "./"

# Cloudflare Pages â€” HTTP bindings
[services]
DOCUSAURUS = { url = "https://wechaty.github.io/docusaurus" }
JEKYLL     = { url = "https://wechaty.github.io/jekyll" }